#Time is based off ticks, 20ticks = 1 second.
Times:
    APPLE: 5
    BREAD: 5
    PORKCHOP: 5
    COOKED_PORKCHOP: 5
    GOLDEN_APPLE: 5
    ENCHANTED_GOLDEN_APPLE: 5
    COD: 5
    COOKED_COD: 5
    SALMON: 5
    COOKED_SALMON: 5
    TROPICAL_FISH: 5
    COOKIE: 5
    MELON_SLICE: 5
    DRIED_KELP: 5
    BEEF: 5
    COOKED_BEEF: 5
    CHICKEN: 5
    COOKED_CHICKEN: 5
    CARROT: 5
    GOLDEN_CARROT: 5
    POTATO: 5
    BAKED_POTATO: 5
    PUMPKIN_PIE: 5
    RABBIT: 5
    COOKED_RABBIT: 5
    RABBIT_STEW: 5
    MUTTON: 5
    COOKED_MUTTON: 5
    BEETROOT: 5
    BEETROOT_SOUP: 5
    SWEET_BERRIES: 5
    HONEY_BOTTLE: 5
    MUSHROOM_STEW: 5
    MILK_BUCKET: 5
    CHORUS_FRUIT: 5
    PUFFERFISH: 5
    ROTTEN_FLESH: 5
    SPIDER_EYE: 5
    POISONOUS_POTATO: 5