#Time is based off ticks, 20ticks = 1 second.
Times:
    APPLE: 10
    BREAD: 10
    PORKCHOP: 10
    COOKED_PORKCHOP: 10
    GOLDEN_APPLE: 10
    ENCHANTED_GOLDEN_APPLE: 10
    COD: 10
    COOKED_COD: 10
    SALMON: 10
    COOKED_SALMON: 10
    TROPICAL_FISH: 10
    COOKIE: 10
    MELON_SLICE: 10
    DRIED_KELP: 10
    BEEF: 10
    COOKED_BEEF: 10
    CHICKEN: 10
    COOKED_CHICKEN: 10
    CARROT: 10
    GOLDEN_CARROT: 10
    POTATO: 10
    BAKED_POTATO: 10
    PUMPKIN_PIE: 10
    RABBIT: 10
    COOKED_RABBIT: 10
    RABBIT_STEW: 10
    MUTTON: 10
    COOKED_MUTTON: 10
    BEETROOT: 10
    BEETROOT_SOUP: 10
    SWEET_BERRIES: 10
    HONEY_BOTTLE: 10
    MUSHROOM_STEW: 10
    MILK_BUCKET: 10